name: Build Test

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: actions

      - name: First say hello
        run: |
          echo hello
